#!/usr/bin/env bash
# classify.sh — Run the AI classification loop for all (or specific) batch files.
#
# Usage:
#   ./classify.sh                                        # Process all batches/library_batch_*.json
#   ./classify.sh --from 3                               # Process batches 3 onwards
#   ./classify.sh --to 5                                 # Process batches 1 through 5
#   ./classify.sh --from 3 --to 7                        # Process batches 3 through 7
#   ./classify.sh batches/library_batch_3.json           # Process a single specific file
#   ./classify.sh batches/new_music_batch_*.json         # Process incremental batches
#
# Prerequisites:
#   - `copilot` CLI installed and authenticated
#   - AGENTS.md present in the project root (copy of prompt.md)
#   - artist_map.json present (generated by `yarn scan`)

set -euo pipefail

MODEL="${COPILOT_MODEL:-claude-sonnet-4.6}"
BATCH_DIR="batches"
FROM=""
TO=""
EXPLICIT_FILES=()

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --from)
      if [[ -z "${2:-}" || ! "${2}" =~ ^[0-9]+$ ]]; then
        echo "❌ --from requires a positive integer argument."
        exit 1
      fi
      FROM="$2"
      shift 2
      ;;
    --to)
      if [[ -z "${2:-}" || ! "${2}" =~ ^[0-9]+$ ]]; then
        echo "❌ --to requires a positive integer argument."
        exit 1
      fi
      TO="$2"
      shift 2
      ;;
    --help|-h)
      sed -n '2,12p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    -*)
      echo "❌ Unknown flag: $1"
      echo "   Run ./classify.sh --help for usage."
      exit 1
      ;;
    *)
      EXPLICIT_FILES+=("$1")
      shift
      ;;
  esac
done

# --from / --to are only meaningful for library batches, not explicit file lists
if [[ ${#EXPLICIT_FILES[@]} -gt 0 && (-n "$FROM" || -n "$TO") ]]; then
  echo "❌ --from / --to cannot be combined with explicit file arguments."
  exit 1
fi

# ---------------------------------------------------------------------------
# Resolve batch files
# ---------------------------------------------------------------------------
if [[ ${#EXPLICIT_FILES[@]} -gt 0 ]]; then
  # Explicit file list passed as positional arguments
  BATCHES=("${EXPLICIT_FILES[@]}")
else
  # Auto-discover library_batch_*.json, sorted numerically
  ALL_BATCHES=()
  while IFS= read -r line; do
    [[ -n "$line" ]] && ALL_BATCHES+=("$line")
  done < <(ls "$BATCH_DIR"/library_batch_*.json 2>/dev/null | sort -t_ -k3 -n || true)

  if [[ ${#ALL_BATCHES[@]} -eq 0 ]]; then
    echo "❌ No batch files found in $BATCH_DIR/. Run 'yarn scan' first to generate them."
    exit 1
  fi

  # Apply --from / --to filters if provided
  if [[ -n "$FROM" || -n "$TO" ]]; then
    BATCHES=()
    for f in "${ALL_BATCHES[@]}"; do
      # Extract the batch number from the filename (library_batch_N.json)
      num=$(basename "$f" | grep -oE '[0-9]+' | head -1)
      if [[ -n "$FROM" && "$num" -lt "$FROM" ]]; then continue; fi
      if [[ -n "$TO"   && "$num" -gt "$TO"   ]]; then continue; fi
      BATCHES+=("$f")
    done

    if [[ ${#BATCHES[@]} -eq 0 ]]; then
      RANGE_MSG=""
      [[ -n "$FROM" ]] && RANGE_MSG+=" --from $FROM"
      [[ -n "$TO"   ]] && RANGE_MSG+=" --to $TO"
      echo "❌ No batch files matched the range:$RANGE_MSG"
      echo "   Available batches: ${ALL_BATCHES[*]}"
      exit 1
    fi
  else
    BATCHES=("${ALL_BATCHES[@]}")
  fi
fi

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
echo "🎵 MP3 Classifier — Copilot CLI batch loop"
echo "   Model  : $MODEL"
echo "   Batches: ${#BATCHES[@]}"
if [[ -n "$FROM" || -n "$TO" ]]; then
  RANGE_MSG="   Range  :"
  [[ -n "$FROM" ]] && RANGE_MSG+=" from $FROM"
  [[ -n "$TO"   ]] && RANGE_MSG+=" to $TO"
  echo "$RANGE_MSG"
fi
echo ""

# ---------------------------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------------------------
if [[ ! -f "AGENTS.md" ]]; then
  echo "⚠️  AGENTS.md not found. The system prompt won't be loaded automatically."
  echo "   Run: cp prompt.md AGENTS.md"
  echo ""
fi

if [[ ! -f "artist_map.json" ]]; then
  echo "❌ artist_map.json not found. Run 'yarn scan' first."
  exit 1
fi

# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------
TOTAL=${#BATCHES[@]}
SUCCESS=0
FAILED=0
FAILED_BATCHES=()

for i in "${!BATCHES[@]}"; do
  BATCH="${BATCHES[$i]}"
  NUM=$((i + 1))

  if [[ ! -f "$BATCH" ]]; then
    echo "⚠️  [$NUM/$TOTAL] Skipping (file not found): $BATCH"
    ((FAILED++)) || true
    FAILED_BATCHES+=("$BATCH")
    continue
  fi

  echo "────────────────────────────────────────────────────────────────────"
  echo "📄 [$NUM/$TOTAL] Processing: $BATCH"
  echo ""

  copilot \
    --model "$MODEL" \
    --yolo \
    --no-ask-user \
    --autopilot \
    -p "Process $BATCH. Read artist_map.json with jq first (query only the artists present in this batch to keep token usage low). Classify all tracks according to your instructions. APPEND results to pending_operations.json — do not overwrite existing entries. Update artist_map.json with any new artist mappings discovered in this batch."

  EXIT_CODE=$?

  if [[ $EXIT_CODE -eq 0 ]]; then
    echo ""
    echo "✅ [$NUM/$TOTAL] Done: $BATCH"
    ((SUCCESS++)) || true
  else
    echo ""
    echo "❌ [$NUM/$TOTAL] Failed (exit $EXIT_CODE): $BATCH"
    ((FAILED++)) || true
    FAILED_BATCHES+=("$BATCH")
  fi

  echo ""
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo "════════════════════════════════════════════════════════════════════"
echo "🏁 Classification complete."
echo "   ✅ Succeeded : $SUCCESS / $TOTAL"
echo "   ❌ Failed    : $FAILED / $TOTAL"

if [[ ${#FAILED_BATCHES[@]} -gt 0 ]]; then
  echo ""
  echo "   Failed batches:"
  for b in "${FAILED_BATCHES[@]}"; do
    echo "     - $b"
  done
  echo ""
  echo "   Re-run failed batches with:"
  echo "     ./classify.sh ${FAILED_BATCHES[*]}"
fi

echo ""
echo "Next steps:"
echo "  yarn stats          # Review classification results"
echo "  yarn backfill:dry   # Preview genre tags before writing"
echo "  yarn backfill       # Write genre tags to MP3 files"
